# https://github.com/tanwanimohit/deploy-react-to-ghpages

name: Deploy App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - run: echo ${{ secrets.REACT_APP_GPT_KEY }}

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
      env:
        REACT_APP_GPT_KEY: ${{ secrets.REACT_APP_GPT_KEY }}